Ftl names
Park-Station/Parkstation pull request #100
Opened 2023-04-20 12:12 UTC by Devianartaro

# Description

Add name and description to locale and in files.

# TODO

# Media

# Changelog

no cl no fun -death

2023-04-20 14:57 UTC, DEATHB4DEFEAT commented
changelog unnecessary

2023-04-20 15:03 UTC, DEATHB4DEFEAT approved these changes

2023-04-22 22:59 UTC, Pspritechologist requested changes
Good changes overall. Sorry to have to clean up our sloppy work :P

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/SimpleStation14/Prototypes/Uplink/uplink-catalog.ftl
> +uplink-armor-hardsuit-desc = A someone damage resistant, but heavy hardsuit that allows eva and protection in fights. Also acts as wizard robes, allowing you to use spells.
```suggestion
uplink-armor-hardsuit-desc = A somewhat damage resistant, but heavy hardsuit that allows eva and protection in fights. Also acts as wizard robes, allowing you to use spells.
```

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-css = As chief supervisor, your main duties would include managing the crew, ensuring that everyone is performing their duties correctly.
There's another PR open for this already, but they have not been responsive.
Take a look at that one to see what the descriptions are, and where the file is.

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/job/job-names.ftl
> +# Nyano
Yes please, thank you.

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/job/job-names.ftl
> +
These should go in the SimpleStation FTL folder. 
Should be Resources/Locale/en-US/SimpleStation14/  if I'm not mistaken.

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/job/job-names.ftl
> +JobChiefServiceSupervisor = chief service supervisor
These should go in the SimpleStation FTL folder.
Should be Resources/Locale/en-US/SimpleStation14/ if I'm not mistaken.

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/prototypes/roles/antags.ftl
> +
These should go in the SimpleStation FTL folder.
Should be Resources/Locale/en-US/SimpleStation14/ if I'm not mistaken.

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Locale/en-US/store/categories.ftl
> +store-category-wands = Wands
These should go in the SimpleStation FTL folder.
Should be Resources/Locale/en-US/SimpleStation14/ if I'm not mistaken.

2023-04-22 22:59 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Traits/abilities.yml
> +  REQUIRES Reptilian species
This looks like an error to me.

2023-04-24 09:50 UTC, OCOtheOmega commented on Resources/Locale/en-US/store/categories.ftl
> +store-category-wands = Wands
better to make categories inside one file

2023-04-24 10:05 UTC, Devianartaro reviewed
i done

2023-04-26 10:10 UTC, Pspritechologist commented
I don't see where the trait FTL strings are in the files, such as trait-monochromacy-name, or trait-mute-description. Are they already elsewhere, or am I just missing them?

Death and I had intended to keep any FTL strings for content we've added in the SimpleStation FTL folder for ease of editing it. I understand this may not be as useful for someone translating. Since translation is the whole point of it, I will speak to him about changing it.

2023-04-26 13:03 UTC, Devianartaro commented
> I don't see where the trait FTL strings are in the files, such as trait-monochromacy-name, or trait-mute-description. Are they already elsewhere, or am I just missing them?
> 
> Death and I had intended to keep any FTL strings for content we've added in the SimpleStation FTL folder for ease of editing it. I understand this may not be as useful for someone translating. Since translation is the whole point of it, I will speak to him about changing it.

There others trait death added but in one commit you remove they, soo i just back it.
https://github.com/Devianartaro/EbenGrad/blob/ftl-names/Resources/Locale/en-US/SimpleStation14/Prototypes/Traits/disabilities.ftl

2023-04-26 19:35 UTC, Pspritechologist approved these changes

2023-04-26 20:32 UTC, DEATHB4DEFEAT approved these changes

2023-04-26 20:33 UTC, merged