Several guidebook changes
Park-Station/Parkstation pull request #127
Opened 2023-05-07 21:50 UTC by DEATHB4DEFEAT

# Description

# TODO

# Media

# Changelog

2023-05-08 02:27 UTC, DEATHB4DEFEAT commented
![image](https://user-images.githubusercontent.com/77995199/236720401-f8b411cf-02e4-4b8f-9384-adaa3d658176.png)

2023-05-11 17:25 UTC, Pspritechologist requested changes

2023-05-11 17:25 UTC, Pspritechologist commented on Resources/Server Info/SimpleStation14/Guidebook/AlertProcedure/StandardOperatingProcedure.xml
> +- XenoBlood
Just a splash of colour? :P

2023-05-11 17:25 UTC, Pspritechologist commented on Resources/Server Info/SimpleStation14/Guidebook/Server/GettingStarted.xml
> +Space Station 14 is a role-playing game at its core- and Parkstation intends to let that fact truly shine. You play as a member of the station crew, which you can customize from the lobby before join
```suggestion
Space Station 14 is a role-playing game at its core- and Parkstation intends to let that fact truly shine. You play as a member of the station crew, which you can customize from the lobby prior to joining the game.
```
\>:P

2023-05-11 17:25 UTC, Pspritechologist commented on Resources/Server Info/SimpleStation14/Guidebook/Server/Parkstation.xml
> +The [color=#334E6D]Head of Personnel[/color] is unrelated to Service and instead serves as the only real Command role. They act as an HR of a type, dealing with overall crew management, IDs, complain
```suggestion
The [color=#334E6D]Head of Personnel[/color] is unrelated to Service and instead occupies Command itself. They act as an HR of a type, dealing with overall crew management, IDs, complaints, and communication among the Heads. Note that they still outrank no Heads, and should instead serve as a binding agent more so than a boss.
```
This was poor wording on my part.

2023-05-19 19:11 UTC, Pspritechologist commented on Resources/Server Info/SimpleStation14/Guidebook/AlertProcedure/StandardOperatingProcedure.xml
> +- XenoBlood
Death you're colouring string.Empty.

2023-08-16 09:25 UTC, Pspritechologist approved these changes

2023-08-16 09:27 UTC, merged