uhhh try to fix tests
Park-Station/Parkstation pull request #130
Opened 2023-05-08 03:46 UTC by DEATHB4DEFEAT

# Description

# TODO

# Media

# Changelog

2023-10-01 22:03 UTC, DEATHB4DEFEAT commented
fake test fails jsndefjksdggskj

2023-10-01 23:27 UTC, Pspritechologist requested changes

2023-10-01 23:27 UTC, Pspritechologist commented on Content.Server/StationEvents/Events/PowerGridCheckRule.cs
This file should be annotated as Parkstation changes.

2023-10-01 23:27 UTC, Pspritechologist commented on Content.Shared/Roles/StartingGearPrototype.cs
> +                if (slot == "socks" && !string.IsNullOrEmpty(_undersocks) && _undersocks != "Error")
"Error" is unintuitive to anyone reading the file :P

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
> +  undersocks: Error
Ditto here

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Objects/Devices/Circuitboards/siliconchargers.yml
> +        Manipulator: 5
Why's this changing?

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Structures/Machines/silicon_chargers.yml
> -      chargeMylti: 150
Are you kidding me :T

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/ServerInfo/SimpleStation14/Guidebook/AlertProcedure/AlertProcedure.xml
> -</Box>
Any reason for this?

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Textures/Clothing/Head/Helmets/syndicate.rsi/meta.json
I'd much rather avoid adding meta files for weird RSIs we don't understand. Can we simply delete the folder and see if it matters?
It wouldn't work at all without the meta, right?

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Textures/Clothing/OuterClothing/Suits/syndicate.rsi/meta.json
Ditto

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Textures/Clothing/OuterClothing/Vests/kevlar.rsi/meta.json
Ditto

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cluwne.rsi/meta.json
Ditto

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Textures/Corvax/Structures/Machines/VendingMachines/ammo.rsi/meta.json
Ditto?

2023-10-01 23:27 UTC, Pspritechologist commented on Resources/Prototypes/SoundCollections/announcements.yml
>    - /Audio/Announcements/RoundEnd/apc_destroyed.ogg
Pretty meh about this one, I'd personally say go without it.

2023-10-01 23:31 UTC, DEATHB4DEFEAT commented on Resources/ServerInfo/SimpleStation14/Guidebook/AlertProcedure/AlertProcedure.xml
> -</Box>
I don't remember

2023-10-01 23:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Objects/Devices/Circuitboards/siliconchargers.yml
> +        Manipulator: 5
Lasers aren't real

2023-10-01 23:35 UTC, DEATHB4DEFEAT commented on Content.Server/StationEvents/Events/PowerGridCheckRule.cs
guh, none of the others were either

2023-10-01 23:48 UTC, DEATHB4DEFEAT commented on Resources/Textures/Corvax/Structures/Machines/VendingMachines/ammo.rsi/meta.json
this one's used

2023-10-02 22:07 UTC, Pspritechologist commented on Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
> +            // _audio.PlayGlobal("/Audio/Misc/notice1.ogg", Filter.Broadcast(), true);
Weird indent stuff?

2023-10-05 01:36 UTC, Pspritechologist approved these changes

2023-10-05 01:37 UTC, merged