Cyborgs Extended
Park-Station/Parkstation pull request #132
Opened 2023-05-08 21:19 UTC by Devianartaro

# Description

# TODO

# Media

# Changelog

Yeah its simple but look good, everything tested, no errors.

![изображение](https://user-images.githubusercontent.com/42233446/236937435-21815bb9-985f-4a2f-b6b0-2a8c89e09035.png)

2023-05-08 22:40 UTC, DEATHB4DEFEAT requested changes
lots of redundant redefinitions

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      map: [ "enum.ToggleVisuals.Layer" ]
Dont know what the base looks like, but only the sprite path looks like it needs to be redefined, everything else would be on the parent

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +        Base: robot-dead
also probably redundant

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
redundant

wish the linter checked for these

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +  - type: CombatMode
combat mode?

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +#     - Cargo
unneeded comment

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: SurvivalKnife # maybe change to ore scaner if upstream add it
probably don't need this and combat mode, I'll let psp decide

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: DrinkWhiskeyBottleFull
some sort of drink holders would be better so it can interact with the bar machinery instead of being one time use

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: DrinkWhiskeyBottleFull
look at the mediborg

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Roles/Jobs/Cyborg/clown_cyborg.yml
> +      time: 24000
clown playtime too

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Roles/Jobs/Cyborg/engineer_cyborg.yml
> +      time: 24000
engineer playtime too

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Roles/Jobs/Cyborg/janitor_cyborg.yml
> +      time: 24000
janitor time too

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Roles/Jobs/Cyborg/security_cyborg.yml
> +      time: 24000
security time too

2023-05-08 22:40 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Roles/Jobs/Cyborg/service_cyborg.yml
> +      time: 24000
bartender time too

2023-05-08 23:02 UTC, Pspritechologist requested changes
This is pretty dang cool, but I am concerned that it only increases the severity of the existing issue with Cyborgs.
The Janitor Cyborg in particular effectively entirely replaces the Janitor themselves in terms of usefulness, they're stronger, better at doing their job, etc.. Cyborgs are fine in a limited extent, but these ones I worry will significantly displace existing jobs.

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: RubberStampClown
I wouldn't want situations of people thinking the Clown has authorized something has legitimate chicanery, but it turns out it was just some lowly Cyborg.

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: BananaPhoneInstrument
This feels like a bad idea :P
Those things are so noisy, and only serve to pester Admins. Linking it to someone's very being feels unnecessary.

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
Needs Clown laws. I might write some up.
These really should also be localized, but I assume the code doesn't support that. Lame.

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +    tools:
No pneumatic launcher for pies??

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: SoapNT
So useless, I love it :P

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
Needs Jani laws

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +  components:
This one *needs* to be made into a solution container, ala a mop bucket, so that they can store puddles in themselves. Then, people can shove them over!

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: FoodCondimentBottleSmallKetchup
😨

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
Needs mining laws, I guess? This is a weird Cyborg :P

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: WeaponDisabler
Can these be charged??

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: Flash
Doesn't this burn out??

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: Handcuffs
CAN THIS BE APPLIED TO PEOPLE??

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/Maps/parkstation.yml
> +        ServiceCyborg: [ 2, 2 ]
This is _so many_ of them :P

2023-05-08 23:02 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Roles/Jobs/Cyborg/clown_cyborg.yml
> +    - !type:OverallPlaytimeRequirement
These should need specific playtime in their respective jobs/as their respective roles. Goes for all of them.

2023-05-09 00:13 UTC, Devianartaro commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - id: Handcuffs
Yeah it can stun and hadcuff target and they dont lost handcuffs

2023-05-09 00:26 UTC, Devianartaro commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +      - Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
Check honk laws

2023-05-09 03:17 UTC, DEATHB4DEFEAT requested changes

2023-05-09 03:17 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/SimpleStation14/Prototypes/job/job-names.ftl
> +job-name-shaftminer-cyborg = ShaftMiner Cyborg
```suggestion
job-name-shaftminer-cyborg = mining cyborg
```

2023-05-09 03:17 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +    netsync: false
server-side sprite component was removed, netsync no longer exists

2023-05-09 03:17 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/borgs.yml
> +    drawdepth: Mobs
redefinition

2023-05-09 13:07 UTC, Devianartaro commented
Yep it need add after IPC merge

2023-08-02 20:32 UTC, OCOtheOmega commented
Well wiz start make own cyborgs, soo this usless.

2023-08-02 20:32 UTC, closed without merging