Shiro's Delight (drink)
Park-Station/Parkstation pull request #134
Opened 2023-05-10 04:53 UTC by SomeCabbage

# Description
Adds in the whacky drink that is Shiro's Delight!

Recipe:
Desoxyephedrine: 5 (drugs)
Ethylredoxrazine: 5 
Doctor's Delight: 5 
Slime: 10 (yummy)
Apple Juice: 5 (abbles)
Makes:
ShirosDelight: 3

Effects:
- Metabolizes about 25% slower
- Satiates hunger
- Satiates thirst
- Gives high amounts of ethanol when over 60u
- Give high amounts of poison when over 60u
- Very minor burn, brute and airloss healing properties
- Go fast
- Stutter
- Narcolepsy resetting above 15u
- Decent knockdown and stun removal

# TODO

# Media
![delight](https://github.com/Park-Station/Parkstation/assets/130223709/6ce0447f-9bce-41bb-9857-1cdc97158f15)
![descript](https://github.com/Park-Station/Parkstation/assets/130223709/6732ee0c-55b1-4b87-82e9-3ab50e5702f6)

# Changelog
:cl: SomeCabbage
- add: Added Shiro's Delight, a fun drink that is time consuming and somewhat difficult to make, but provides funny buffs

2023-05-10 04:59 UTC, DEATHB4DEFEAT requested changes
hehe draft review

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/flavors/flavor-profiles.ftl
> +## parkstation
```suggestion
## Parkstation
```

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Consumable/Drinks/flasks.yml
> +              Quantity: 30
should this be in the flasks.yml file?

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Recipes/Reactions/chemicals.yml
> +    Desoxyephedrine: #meth
```suggestion
    Desoxyephedrine: # Meth
```
nitpicky :)

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Recipes/Reactions/chemicals.yml
> +    Ethylredoxrazine: #negating the alcohol effects of the delight
```suggestion
    Ethylredoxrazine: # Negating the alcohol effects of the delight
```

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Recipes/Reactions/chemicals.yml
> +    DoctorsDelight: #delight and negating the poison of the meth
```suggestion
    DoctorsDelight: # Delight and negating the poison of the meth
```

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Recipes/Reactions/chemicals.yml
> +    Slime: #squish tasty
```suggestion
    Slime: # Squish tasty
```

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Recipes/Reactions/chemicals.yml
> +    JuiceApple: #add just that little bit of extra work
```suggestion
    JuiceApple: # Add just that little bit of extra work
```

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Textures/SimpleStation14/Objects/Consumable/Drinks/shirosdelightglass.rsi/meta.json
> +    "copyright": "Made by Cabbage#9633",
```suggestion
    "copyright": "Made by DSC@Cabbage#9633 (561159087765848084)",
```

2023-05-10 04:59 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Reagents/drinks.yml
Overdoses are pretty high

2023-05-10 05:08 UTC, SomeCabbage commented on Resources/Prototypes/SimpleStation14/Entities/Consumable/Drinks/flasks.yml
> +              Quantity: 30
changing it now

2023-05-10 05:08 UTC, SomeCabbage commented on Resources/Prototypes/SimpleStation14/Reagents/drinks.yml
changed them to be actually attainable by normal drinking

2023-05-11 17:42 UTC, Pspritechologist approved these changes

2023-05-11 17:46 UTC, ashkitten commented on Resources/Prototypes/SimpleStation14/Entities/Consumable/Drinks/drinks.yml
> +  description: A swirling solution with the slimy dissociation of an extraordinary paramedic. Due to it's thick nature it lingers in the body a bit longer than usual. Overdrinking is incredibly dange
```suggestion
  description: A swirling solution with the slimy dissociation of an extraordinary paramedic. Due to its thick nature it lingers in the body a bit longer than usual. Overdrinking is incredibly dangerous.
```

2023-05-11 17:46 UTC, ashkitten commented on Resources/Prototypes/SimpleStation14/Reagents/drinks.yml
> +  desc: It swirls with the slime and dissociation of an extraordinary paramedic. Due to it's thick nature it lingers in the body a bit longer than usual. Overdrinking is incredibly dangerous.
```suggestion
  desc: It swirls with the slime and dissociation of an extraordinary paramedic. Due to its thick nature it lingers in the body a bit longer than usual. Overdrinking is incredibly dangerous.
```

2023-05-11 19:01 UTC, DEATHB4DEFEAT approved these changes

2023-05-11 19:01 UTC, merged