New AI Features
Park-Station/Parkstation pull request #143
Opened 2023-05-17 03:47 UTC by Pspritechologist

# Description
Adds some cool new stuff to the AI, including random screens and laws on startup.

# TODO
- [ ] Make a TODO list

# Media
TBD

# Changelog

:cl:
- add: Added fun!
- tweak: Tweaked fun!
- fix: Fixed fun!
- remove: Removed fun!

2023-05-17 21:59 UTC, DEATHB4DEFEAT commented on Resources/Textures/SimpleStation14/Mobs/Silicon/ai.rsi/ai-not malf.png
file/folder names should never have a space

2023-05-19 00:51 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
> +    Tyrant: 0.10
At 7.0 and 6.0 for Crewsimov and Asimov++, the AI had funny laws 33% of the time in a sample size of 60. I tweaked the values a little higher, and I'm completely up for discussing them.

The other values were selected based on a ranking list of which lawsets are most "viable" for a station. For instance, Druid and Mother are weird, but perfectly viable to a smooth round, thus 0.6. All the 0.40 lawsets are _fine_, and generally prioritize crew health and happiness, but are very limiting in their scope and somewhat unpredictable. The 0.25s like the Clown, Robocop, etc., are goofier and less viable for actually running a station, being extremely limited in scope of focus. Finally, Tyrant is just dangerous :P

2023-05-19 08:52 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
> +    Tyrant: 0.10
The code preview doesn't seem to have updated for me, but the files chanced did, so look there for the actual values if the preview seems off.

2023-05-19 08:54 UTC, Pspritechologist commented
@DEATHB4DEFEAT Needs some discussion. Giving the AI a face that reacts to current power, and a face that reacts to damage, *as well* as it being random is going to be a fair bit of extra work. I'm willing to do it, but there's some other stuff in here that I feel takes priority. Those future changes can probably come with the IPC merge, when the AI actually requires power to live consistently. 
Other than that, I need to clean up the file names (give me your rename script pls <3), and get your opinion on the law weights (other comment).

2023-05-20 04:21 UTC, DEATHB4DEFEAT commented
and that is why you can't have spaces (rsi diff bot)

2023-05-20 09:14 UTC, Pspritechologist commented
Assuming all the sprites work, this is probably in the best state it'll be for a bit. Battery simply doesn't work, AI maybe draws power(??), no idea really. Powernet is hard.
This'll be improved upon once SiliconComponent is in and the AI can live off battery, so my focus likely return to there now that I've scratched my distraction itch.

To sum up, yell at me if this can't be merged yet.

2023-05-21 06:07 UTC, DEATHB4DEFEAT requested changes
spaces !!!!!!!!!!

2023-05-21 06:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
> +    - "Secondly, consider the crew dear to me; to live in common with them and, if necessary, rish my existence for them."
```suggestion
    - "Secondly, consider the crew dear to me; to live in common with them and, if necessary, risk my existence for them."
```

2023-05-21 06:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
> +    - "in addition, do not intervene in situations i am not knowledgeable, even for patients in whom the harm is manifest, leave this operation to be preformed by specialists. "
```suggestion
    - "In addition, do not intervene in situations I am not knowledgeable, even for patients in whom the harm is manifest, leave this operation to be performed by specialists. "
```

2023-05-21 06:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
> +    - "Finally, all that may come to me un the exorcize of my profession or in daily commerce with the crew, shouod it not be spread abroad, keep secret and never reveal."
```suggestion
    - "Finally, all that may come to me while I exercise my profession or in daily commerce with the crew, should it not be spread abroad, keep secret and never reveal."
```

2023-05-21 06:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
> +    - "In addendum, if i keep these laws faithfully, may i enjoy my life, respected by all humanity, but if I swerve from it or violate it, may I suffer and be expunged."
```suggestion
    - "In addendum, if I keep these laws faithfully, may I enjoy my life, respected by all humanity, but if I swerve from it or violate it, may I suffer and be expunged."
```

2023-05-21 06:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Laws/sailawsets.yml
locale

2023-05-21 06:07 UTC, DEATHB4DEFEAT commented on Content.Server/Borgs/LawsSystem.cs
> +            // component.Laws.Clear();
//

2023-06-09 12:07 UTC, merged