Prescription Security glasses
Park-Station/Parkstation pull request #159
Opened 2023-05-30 04:27 UTC by SomeCabbage

The old PR broke so I redid it.

# Description

Adds prescription security glasses
they have a small chance to fall off your face when you slip. Small enough that it wont be a problem normally but just enough so that it'll be noticeable

Adds 2 units to SecTech
Adds to loadouts for 4 points

# Media
![image](https://github.com/Park-Station/Parkstation/assets/130223709/20294b62-9bb8-4efa-ba06-2deba8202eb7)

# Changelog

:cl: SomeCabbage
- add: Added prescription engineering goggles and put them into the department vending machine and loadout selection.

2023-05-31 10:50 UTC, Pspritechologist requested changes

2023-05-31 10:50 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Clothing/Eyes/glasses.yml
> +    chance: 5
```suggestion
    chance: 5
    
```

2023-05-31 10:50 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Entities/Clothing/Eyes/glasses.yml
> +  parent: ClothingEyesBase
Parent from Secglasses, and remove the redundant components. Just add the prescription glasses thing and the drop chance.

2023-05-31 10:50 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Loadouts/traits.yml
Make sure this is in the same order as the other loadouts. I believe I ordered them something like Department alphabetically? Not certain, just try to find the pattern and match it.

2023-05-31 10:50 UTC, Pspritechologist commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
> +    ClothingEyesGlassesSecurityPrescription: 2
Move this to the bottom. Just for the sake of organization (and merge conflicts), it's nice to have anything we add at the bottom of a list.

2023-05-31 14:51 UTC, SomeCabbage commented on Resources/Prototypes/SimpleStation14/Loadouts/traits.yml
you mean the whitelisted jobs list?

2023-05-31 14:54 UTC, SomeCabbage commented on Resources/Prototypes/SimpleStation14/Loadouts/traits.yml
for other items it seems to be based off the "rank" or for epistemics items its just a list of the

2023-05-31 14:59 UTC, SomeCabbage commented on Resources/Prototypes/SimpleStation14/Loadouts/traits.yml
I just did it in alphabetical order this time

2023-06-06 23:05 UTC, Pspritechologist approved these changes

2023-06-06 23:06 UTC, Pspritechologist commented
Update the pr description before merge.
It probably doesn't need a changelog.

2023-06-06 23:22 UTC, SomeCabbage commented
no more changelog

2023-06-07 06:03 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Loadouts/traits.yml
> +      - Nearsighted
I wonder if this works as intended (if it doesn't I'm going to explode, hold on)

2023-06-07 06:04 UTC, DEATHB4DEFEAT approved these changes

2023-06-07 06:04 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Loadouts/traits.yml
> +      - Nearsighted
alright I am good coder man

2023-06-07 06:05 UTC, merged