Drop on slip fix
Park-Station/Parkstation pull request #160
Opened 2023-05-31 09:13 UTC by Pspritechologist

# Description
Fixes the DropOnSlipSystem to actually work now.
It also improves it, so now your items go flying when you drop them! :)

Requires #113 

# Changelog

:cl:
- add: Added fun!
- tweak: Tweaked fun!
- fix: Fixed fun!
- remove: Removed fun!

2023-05-31 15:02 UTC, DEATHB4DEFEAT commented
2794 files changed moment

2023-05-31 15:03 UTC, SomeCabbage commented
oh jeezus christ

2023-06-14 14:07 UTC, Pspritechologist commented
> 2794 files changed moment

:)

2023-06-16 04:44 UTC, DEATHB4DEFEAT requested changes

2023-06-16 04:44 UTC, DEATHB4DEFEAT commented on Content.Shared/Slippery/SlipperySystem.cs
> +// Parkstation-DropOnSlip-Start
no ending tag?

2023-06-16 06:22 UTC, Pspritechologist commented on Resources/Locale/en-US/SimpleStation14/Content/Slippery/dropOnSlip.ftl
>  system-drop-on-slip-text-clumsy = The {$item} tumbles off of {$name}!
This should use the localization THE thing

2023-06-16 06:33 UTC, Pspritechologist commented on Content.Shared/Slippery/SlipperySystem.cs
> +public readonly record struct ParkSlipEvent(EntityUid Tripper);
```suggestion

// Parkstation-DropOnSlip-Start
/// <summary>
///     This is an event raised on an entity after they slip. Duh.
/// </summary>
public readonly record struct ParkSlipEvent(EntityUid Tripper);
// Parkstation-DropOnSlip-End
```

2023-06-16 06:35 UTC, DEATHB4DEFEAT approved these changes
yippee

2023-06-25 10:48 UTC, merged