Parkstation tweaks
Park-Station/Parkstation pull request #21
Opened 2023-01-30 09:08 UTC by Pspritechologist

Glasses fall of when you slip, and take damage when thrown around, hit, or stepped on.
Adds a chance variable to allow only taking damage when thrown sometimes.
Added suffixes to the psionic clothing.

2023-01-30 16:09 UTC, DEATHB4DEFEAT requested changes
cool

2023-01-30 16:09 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Damage/Systems/DamageOnTriggerSystem.cs
> +        // }
what's this for?

2023-01-30 16:09 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  # - type: DropOnSlip
random comment

2023-01-30 21:05 UTC, Pspritechologist commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  # - type: DropOnSlip
Help me work out how to test for a component on an item in an item slot and it won't be random :P

2023-01-31 22:10 UTC, DEATHB4DEFEAT approved these changes

2023-02-02 11:19 UTC, merged