Adds Punpun
Park-Station/Parkstation pull request #48
Opened 2023-03-08 20:36 UTC by Pspritechologist

The Bartender's monkey, Punpun grows in numerance with each passing shift he manages to survive, and holds on to any hats or masks he's given for the next shift, taking ownership of them. At the fourteenth shift, he takes a well needed break and comes back refreshed.

To do is add a note claiming his vacationage, and making something more interesting happen for the fourteenth Punpun?

2023-03-08 23:00 UTC, DEATHB4DEFEAT requested changes

2023-03-08 23:00 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +    public string checkSlot(EntityUid uid, string slot)
```suggestion
    private string checkSlot(EntityUid uid, string slot)
```

2023-03-08 23:00 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Objects/Misc/paper.yml
> +      I, punpun, invoke my right to have all of my clones on the NT family vacation to the meat packaging plant one out of every 15 shifts.
```suggestion
      I, Punpun, invoke my right to have all of my clones on the NT family vacation to the meat packaging plant one out of every 15 shifts.
```

2023-03-08 23:00 UTC, DEATHB4DEFEAT commented on Resources/Textures/SimpleStation14/Mobs/Pets/punpun.rsi/meta.json
> +  "copyright": "Taken from TGStation",
Link to commit

2023-03-08 23:03 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +    public string checkSlot(EntityUid uid, string slot)
Capitalize function name too

2023-03-08 23:23 UTC, DEATHB4DEFEAT requested changes

2023-03-08 23:23 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +public class PunpunSystem : EntitySystem
```suggestion
public sealed class PunpunSystem : EntitySystem
```

2023-03-08 23:23 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +        base.Initialize();
```suggestion
        base.Initialize();
        
```

2023-03-08 23:23 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +    }
```suggestion
    private string CheckSlot(EntityUid uid, string slot)
    {
        if (_inventorySystem.TryGetSlotEntity(uid, slot, out var item) && item != null)
            return _entityManager.GetComponent<MetaDataComponent>(item.Value).EntityPrototype!.ID;
        
        return String.Empty;
    }
```

2023-03-08 23:23 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +        }
```suggestion
        else _entityManager.DeleteEntity(itemEnt);
```

2023-03-08 23:23 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +            punpunData.Item3 = checkSlot(uid, "mask");
```suggestion
            punpunData.Item2 = CheckSlot(uid, "head");
            punpunData.Item3 = CheckSlot(uid, "mask");
```

2023-03-09 06:49 UTC, DEATHB4DEFEAT requested changes
nitpicking :)

2023-03-09 06:49 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +            return;
```suggestion

            return;
```

2023-03-09 06:49 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +        metaCompEnt.EntityName = name + " " + numerals[punpunData.Item1];
```suggestion

        metaCompEnt.EntityName = name + " " + numerals[punpunData.Item1];
```

2023-03-09 06:49 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Punpun/PunpunSystem.cs
> +            metaCompItem.EntityName = EntityManager.GetComponent<MetaDataComponent>(uid).EntityName + "'s " + itemName;
```suggestion

            metaCompItem.EntityName = EntityManager.GetComponent<MetaDataComponent>(uid).EntityName + "'s " + itemName;
```

2023-03-10 06:18 UTC, DEATHB4DEFEAT approved these changes
lgtm

2023-03-10 06:21 UTC, DEATHB4DEFEAT commented
looks like you had further plans, merge whenever you want
in the future draft prs if you don't want it merged

2023-03-11 09:51 UTC, Pspritechologist commented
I don't think I did? Believe this one is done

2023-03-19 04:32 UTC, DEATHB4DEFEAT commented
what's up with the changed files?

2023-03-24 04:11 UTC, Pspritechologist commented
> what's up with the changed files?

Pulling issues. I'll rebase this, that should fix it.

2023-03-24 04:19 UTC, Pspritechologist commented
@DEATHB4DEFEAT :D

2023-03-24 04:34 UTC, DEATHB4DEFEAT approved these changes

2023-03-24 04:36 UTC, merged