Sounds
Park-Station/Parkstation pull request #55
Opened 2023-03-25 21:16 UTC by DEATHB4DEFEAT

## About the PR

Adds several pickup/drop/throw sounds for items, some being boxes, toolboxes, belts, tools, ammo boxes
Adds hit sounds for Katana, Captain Sabre, and Banjo

**Media**

uh

2023-03-26 10:08 UTC, Pspritechologist requested changes
Overall, I'd actually really like to see _more_ sounds before this gets ported. More dishware, more clothes, plushies, etc.. Those were some of the gaps I noticed very quickly.
This is a really good change.

2023-03-26 10:08 UTC, Pspritechologist commented on Content.Server/Roles/Cryostasis.cs
Since this change is pretty apart from all the sound additions, we should move it to a seperate PR for the sake of commit history.

2023-03-26 10:08 UTC, Pspritechologist commented on Content.Server/SimpleStation14/Administration/Commands/BriefCommand.cs
Ditto

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Audio/Announcements/announce.ogg
I don't actually know where this file gets used, so my immediate concern would be consistency, as I know some alerts have the original announcement sound simply in them.

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Audio/Announcements/welcome.ogg
Anything changing announcer sounds should be removed for upcoming changes.

Also, don't do Neil dirty like that :(

2023-03-26 10:08 UTC, Pspritechologist commented on Content.Server/StationEvents/Events/AnomalySpawn.cs
> +        ChatSystem.DispatchGlobalAnnouncement(str, announcementSound: new SoundPathSpecifier("/Audio/SimpleStation14/Announcements/voxfem/anomalies.ogg"), colorOverride: Color.FromHex("#18abf5"));
I like the announcement, but I dislike the lack of consistency between them. 
Also, the announcer thing I mentioned in welcome.ogg

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Prototypes/SimpleStation14/Voice/speech_emotes.yml
> +    - crackles!
Really?

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
> +    sound: /Audio/SimpleStation14/Items/Handling/sword_unsheath.ogg
It bothers me too much that quick equip doesn't play equipping sounds.
The sword literally plays the unsheathing noise in any context EXCEPT FOR UNSHEATHING IT

Fixing that issue would make this fine.

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    delay: 15
Ok yes, funny :P

That said, the sound is too long for me to be totally fine with this. Isn't there an arming sound or something?

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/base_ammo.yml
Yeah alright, fair enough :p

2023-03-26 10:08 UTC, Pspritechologist commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
Make this change to some other entities as well, like mugs.

Bonus points if you can get some other dishware in there with other sounds.

2023-03-26 12:34 UTC, DEATHB4DEFEAT commented on Resources/Audio/Announcements/announce.ogg
comms console

2023-03-26 21:43 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    delay: 15
there is
short beep for the keypad
long beep for ready to arm
the alert level for armed
this for detonating

I saw detonating as the best one, lowered its volume a lot and made a 15-second cooldown which I'd be fine to increase

2023-04-09 03:48 UTC, Pspritechologist approved these changes

2023-04-09 05:25 UTC, Pspritechologist approved these changes

2023-04-09 05:28 UTC, merged