Fix cloning not adding traits
Park-Station/Parkstation pull request #67
Opened 2023-04-03 01:16 UTC by DEATHB4DEFEAT

# About the PR

Makes TraitSystem into something usable by other systems
Uses TraitSystem in CloningSystem to add traits to the clones
Emits a BeingCloned event (todo)

# Changelog

:cl: DEATHB4DEFEAT
- fix: Fixed cloning not applying traits.

2023-04-03 03:50 UTC, Pspritechologist requested changes
This seems like a really good change, and like it makes a lot of sense for a system that is frankly somewhat archaic. but do you worry it will be annoying to maintain at all? I feel this belongs on an Upstream PR before we merge it ourselves.

2023-04-03 03:50 UTC, Pspritechologist commented on Content.Server/Traits/TraitSystem.cs
>      };
Feel like this should either be a YAML, or a true/false in the YAML for the role or entity.

2023-04-03 03:50 UTC, Pspritechologist commented on Content.Server/Traits/TraitSystem.cs
>          }
This should give some player feedback, even if it's minor. Something pasted in chat or whatever could be good, maybe a message from [server]. Just so they have a way of knowing what happened.

2023-04-07 01:27 UTC, DEATHB4DEFEAT commented
> do you worry it will be annoying to maintain at all? I feel this belongs on an Upstream PR before we merge it ourselves.

I have accepted I will need to maintain the many changes I have made to the trait systems.
If wizden fixes the trait cloning, good for them, we can see how they did it and maybe modify my changes.

2023-04-09 03:17 UTC, Pspritechologist approved these changes

2023-04-09 03:42 UTC, merged