Update PR and Issue templates
Park-Station/Parkstation pull request #83
Opened 2023-04-07 01:23 UTC by DEATHB4DEFEAT

# About the PR

Modifies the PR and Issue templates to look nicer and fit better.
Look at the changed files to see the new versions.

2023-04-07 22:53 UTC, Pspritechologist requested changes

2023-04-07 22:53 UTC, Pspritechologist commented on .github/PULL_REQUEST_TEMPLATE.md
> +If you include media in your pull request, we may potentially use it in the progress reports, with clear credit given.
This is not true :P

2023-04-07 22:53 UTC, Pspritechologist commented on .github/PULL_REQUEST_TEMPLATE.md
> -Use screenshot software like Window's built in snipping tool, ShareX, Lightshot, or recording software like ShareX (gif), ScreenToGif, or Open Broadcaster Software (cross platform).
I 100% understand your perspective for removing this line, but you need to keep in mind your position and where you're coming from.

This is, and I promise you I'm being honest, _not_ as obvious as you think it is to anyone who might be making a PR.

2023-04-09 06:30 UTC, Pspritechologist approved these changes

2023-04-09 06:30 UTC, DEATHB4DEFEAT commented on .github/PULL_REQUEST_TEMPLATE.md
> +A checklist can be make using the following syntax:
```suggestion
A checklist can be made using the following syntax:
```

2023-04-09 06:30 UTC, merged