adds localization and description to css and updates hop description regarding leading service
Park-Station/Parkstation pull request #90
Opened 2023-04-12 11:42 UTC by rbertoche

# Description

# TODO

# Media

# Changelog

2023-04-12 12:03 UTC, rbertoche commented
does css supervises quartermasters? prototype still says it's hop, I just assumed it since qm is not command

2023-04-12 21:45 UTC, DEATHB4DEFEAT commented
> does css supervises quartermasters? prototype still says it's hop, I just assumed it since qm is not command 

Quartermaster is a normal service job, CSS supervises them

2023-04-12 21:47 UTC, DEATHB4DEFEAT requested changes

2023-04-12 21:47 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-hop = Handle access reassignment fairly using your ID console, keep departments enough and well staffed, and keep Ian safe.
```suggestion
job-description-hop = Handle access reassignment fairly using your ID console, keep departments well staffed, and keep Ian safe.
```

2023-04-12 21:47 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-css = Lead the service department which includes cargo and make sure all that the crew needs the most is provided and made available when necessary.
```suggestion
job-description-css = Lead the service department and make sure all things the crew needs are provided and made available when necessary.
```

2023-04-12 21:48 UTC, DEATHB4DEFEAT commented
Should make changelog entries

2023-04-13 01:55 UTC, rbertoche commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-hop = Handle access reassignment fairly using your ID console, keep departments enough and well staffed, and keep Ian safe.
requested change to weird phrasing

2023-04-13 01:55 UTC, rbertoche commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-hop = Handle access reassignment fairly using your ID console, keep departments enough and well staffed, and keep Ian safe.
uhhh
wrong text box

2023-04-13 01:58 UTC, DEATHB4DEFEAT approved these changes

2023-04-13 02:01 UTC, Pspritechologist requested changes
Move them to a SimpleStation14 .ftl file, should already be a folder structure for us in there. Other than that, good change, keepin' it tidy 👍

2023-04-13 02:01 UTC, Pspritechologist commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-hop = Handle access reassignment fairly using your ID console, keep departments well staffed, and keep Ian safe.
```suggestion
job-description-hop = Handle access reassignment fairly using your ID console, communicate among the crew and Heads, and keep Ian safe.
```

2023-05-01 04:16 UTC, Pspritechologist commented
Taken care of by #100 and inactive.

2023-05-01 04:16 UTC, closed without merging

2023-05-11 02:34 UTC, rbertoche commented
cool. o/