Interpersonal Conflict
Park-Station/Parkstation pull request #97
Opened 2023-04-20 05:10 UTC by Pspritechologist

# Description
Adds IPCs!
Description to be updated later.

# TODO

# Media

# Changelog

:cl:
- add: Added fun!
- tweak: Tweaked fun!
- fix: Fixed fun!
- remove: Removed fun!

2023-04-21 06:26 UTC, DEATHB4DEFEAT requested changes
crin**g**nt

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +    // [Dependency] private readonly MovementSpeedModifierSystem _movementSpeedModifierSystem = default!;
//

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/BedSystem.cs
> +                    if (EntityManager.TryGetComponent<SleepingComponent>(healedEntity, out var sleepComp) && sleepComp.Heal)
‫

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +    static string popupOverheating = Loc.GetString("silicon-system-overheating");
unnecessary static definition

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +        SubscribeLocalEvent<BatteryComponent, ComponentInit>(OnBatteryInit);
```suggestion
        // I hate dual subscriptions
        SubscribeLocalEvent<BatteryComponent, ComponentInit>(OnBatteryInit);
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +                continue;
could use a .Where() on the query

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +            // All multipliers will be - 1, and then added together, and then multiplied by 150. This is then added to the base drain rate.
```suggestion
            // All multipliers will be subtracted by 1, and then added together, and then multiplied by the drain rate. This is then added to the base drain rate.
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +            //TODO: Devise a method of adding multis where other systems can alter the drain rate.
```suggestion
            // TODO: Devise a method of adding multis where other systems can alter the drain rate.
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +            // DebugTools.Assert("Silicon has no temperature component, but is battery powered.");
//

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +        var siliconComp = EntityManager.GetComponent<SiliconComponent>(silicon);
```suggestion

        var siliconComp = EntityManager.GetComponent<SiliconComponent>(silicon);
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +
```suggestion

```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +                // Logger.WarningS("silicon", $"Silicon {silicon} has a {Math.Clamp(temperComp.CurrentTemperature / (upperThresh * 15), 0.001f, 0.9f)} chance to catch fire, and a {Math.Clamp(temperCo
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +            var chargeRate = frameTime * chargerComp.ChargeMulti / chargerComp.PresentEntities.Count ;
floatin
```suggestion
            var chargeRate = frameTime * chargerComp.ChargeMulti / chargerComp.PresentEntities.Count;
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +        batteryComp.CurrentCharge < batteryComp.MaxCharge)
```suggestion
            !EntityManager.TryGetComponent<UnremoveableComponent>(entity, out var _) &&
            batteryComp.CurrentCharge < batteryComp.MaxCharge)
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +        // Do some math so a charger never charges a battery in less than 10 seconds, just for the effect of it.
maybe a minchargetime variable or something

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +        if (damageDealt != null && chargerComp.warningAccumulator <= 0 && damageDealt.Total > 0)
```suggestion

        if (damageDealt != null && chargerComp.warningAccumulator <= 0 && damageDealt.Total > 0)
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/Bed/Sleep/SleepingComponent.cs
//

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Components/SiliconComponent.cs
> +///     Component for defnining a mob as a robot.
```suggestion
///     Component for defining a mob as a robot.
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Systems/SharedSiliconSystem.cs
> +// using
```suggestion
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Systems/SharedSiliconSystem.cs
> +namespace Content.Shared.SimpleStation14.Silicon.Systems;
```suggestion
namespace Content.Shared.SimpleStation14.Silicon.Systems;

```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Systems/SharedSiliconSystem.cs
> +        if (component.BatteryPowered)
invert if

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Systems/SharedSiliconSystem.cs
> +                    closest = ((float)state.Key);
```suggestion
                if (component.ChargeState >= state.Key && ((float) state.Key) > closest)
                    closest = ((float) state.Key);
```

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Systems/SharedSiliconSystem.cs
> +// }
//

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Body/Organs/ipc.yml
> +  - type: Organ
added by parent

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Body/Parts/ipc.yml
> +# TODO BODY: Part damage
//

2023-04-21 06:26 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/silicon_base.yml
> +  id: PlayerSiliconBase #for player controlled silicons
```suggestion
  id: PlayerSiliconBase # For player controlled silicons
```

2023-05-22 11:50 UTC, Pspritechologist commented on Content.Shared/SimpleStation14/Silicon/Systems/SharedSiliconChargerSystem.cs
> +    public void UpdateState(EntityUid uid, SiliconChargerComponent? component = null)
@DEATHB4DEFEAT Let me know if you know of anyway to use this the way I need to, without making it Public.

2023-06-22 23:29 UTC, caucasianhamburger commented
i will watch your career with great interest

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/Electrocution/ElectrocutionSystem.cs
spess

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Components/BatteryDrinkerComponent.cs
> +    ///     Is mutliplied by the source.
```suggestion
    ///     Is multiplied by the source.
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Components/BatteryDrinkerComponent.cs
> +    public string DrinkText = "aaaaaaaaaa";
aaaaaaaaaa

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Systems/BatteryDrinkerSystem.cs
> +
```suggestion
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Systems/BatteryDrinkerSystem.cs
> +        }
```suggestion
        if (sourceComp != null && sourceComp.MaxAmount > 0)
            amountToDrink = MathF.Min(amountToDrink, (float) sourceComp.MaxAmount);
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Systems/BatteryElectrocuteChargeSystem.cs
> +        _popup.PopupEntity(message, uid, uid);
```suggestion
        _popup.PopupEntity(Loc.GetString("battery-electrocute-charge"), uid, uid);
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +        }
```suggestion
        if (args.ChargeState == ChargeState.Dead && !siliconDeadComp.Dead)
            SiliconDead(uid, siliconDeadComp, batteryComp);
        else if (args.ChargeState != ChargeState.Dead && siliconDeadComp.Dead)
            SiliconUnDead(uid, siliconDeadComp, batteryComp);
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +    private void SiliconUnDead(EntityUid uid, SiliconDownOnDeadComponent siliconDeadComp, BatteryComponent batteryComp)
funny name :+1:

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
> +///     A canellable event raised when a Silicon is about to go down due to charge.
```suggestion
///     A cancellable event raised when a Silicon is about to go down due to charge.
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
event in event file D:

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +        var entstorQuery = EntityQueryEnumerator<SiliconChargerComponent, EntityStorageComponent>();
```suggestion
        var entityStorageQuery = EntityQueryEnumerator<SiliconChargerComponent, EntityStorageComponent>();
```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +
```suggestion

                HandleChargingEntity(entity, chargeRate, chargerComp, uid, frameTime);


```

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +        // Do some math so a charger never charges a battery from zero to full in less than 10 seconds, just for the effect of it.
berryable

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Server/Temperature/Systems/TemperatureSystem.cs
wtf go to wiz

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Shared/Humanoid/SkinColor.cs
ffffikcs

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
uptream?

2023-06-23 04:25 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/SimpleStation14/Prototypes/Entities/Mobs/Customization/ipcScreens.ftl
> +marking-ScreenMonoeye = Cylops
```suggestion
marking-ScreenMonoeye = Cyclops
```

2023-06-24 03:25 UTC, Pspritechologist commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
cope

2023-06-24 05:20 UTC, Pspritechologist commented on Content.Server/Electrocution/ElectrocutionSystem.cs
Huh?

2023-06-24 05:21 UTC, Pspritechologist commented on Content.Server/Temperature/Systems/TemperatureSystem.cs
Likely not a pr worth making at this point. Quite a few people have expressed interest in IPC, so it might make its way there anyway.

2023-06-24 05:22 UTC, Pspritechologist commented on Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
Ditto, honestly.

2023-06-25 10:34 UTC, Pspritechologist commented on Content.Server/Station/Systems/StationSpawningSystem.cs
> +            // Resolve SharedContainerSystem
```suggestion
```

2023-06-25 10:38 UTC, Pspritechologist commented on Content.Shared/Humanoid/SkinColor.cs
>      {
```suggestion
    {
        // Parkstation-IPC-Start
```

2023-06-25 10:38 UTC, Pspritechologist commented on Content.Shared/Humanoid/SkinColor.cs
> +        return Color.FromHsv(hsv);
```suggestion
        return Color.FromHsv(hsv);
        Parkstation-IPC-End
```

2023-06-25 10:39 UTC, Pspritechologist commented on Content.Shared/Humanoid/SkinColor.cs
>      {
```suggestion
    {
        // Parkstation-IPC-Start
```

2023-06-25 10:39 UTC, Pspritechologist commented on Content.Shared/Humanoid/SkinColor.cs
> +        return hsv.Y <= 0.6 && hsv.Z >= 0.25;
```suggestion
        return hsv.Y <= 0.6 && hsv.Z >= 0.25;
        // Parkstation-IPC-End
```

2023-07-15 10:44 UTC, DEATHB4DEFEAT requested changes
- Need random names
- Age max change
- Remove marking points (there are no markings enabled)
- alerts-charge-desc
- Robot typing indicator
- Broken charging pad
- No guidebook entry

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Components/RandomBatteryChargeComponent.cs
> +    ///     True if the current charge is based on the preexisting current charge, or false if it's based on the max charge.
is this ture?

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Power/Systems/SiliconEmitSoundOnDrainedSystem.cs
> +        // If you give something the EmitSoundOnCritComponent, know that it can't have the SpamEmitSoundComponent, and any other systems that play with it will just be broken.
```suggestion
        // If you give something the SiliconEmitSoundOnDrainedComponent, know that it can't have the SpamEmitSoundComponent, and any other systems that play with it will just be broken.
```

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Components/BatteryDrinkerSourceComponent.cs
> +    ///     The sound to play when the APC gets drunk from.
```suggestion
    ///     The sound to play when the battery gets drunk from.
```

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +            if (siliconComp.EntityType.Equals(SiliconType.Npc))
```suggestion
            if (siliconComp.EntityType == SiliconType.Npc)
```

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +            if (!siliconComp.EntityType.Equals(SiliconType.Npc)) // Don't bother checking heat if it's an NPC. It's a waste of time, and it'd be delayed due to the update time.
```suggestion
            if (!siliconComp.EntityType == SiliconType.Npc) // Don't bother checking heat if it's an NPC. It's a waste of time, and it'd be delayed due to the update time.
```

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargerSystem.cs
> +            if (batteryComp.CurrentCharge < batteryComp.MaxCharge)
do the batteries still explode?

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Silicon/Components/SiliconChargerComponent.cs
> +    ///     The current parts mutliplier.
```suggestion
    ///     The current parts multiplier.
```

2023-07-15 10:44 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/revenant/revenant.ftl
> +# UI
```suggestion
#UI
```

2023-07-24 22:52 UTC, Pspritechologist commented on Content.Server/SimpleStation14/Power/Components/RandomBatteryChargeComponent.cs
> +    ///     True if the current charge is based on the preexisting current charge, or false if it's based on the max charge.
Better?

2023-07-24 22:53 UTC, Pspritechologist commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeDeathSystem.cs
Nahh

2023-07-24 22:54 UTC, Pspritechologist commented on Content.Server/SimpleStation14/Silicon/Charge/Systems/SiliconChargeSystem.cs
> +            if (siliconComp.EntityType.Equals(SiliconType.Npc))
Can't, since EntityType is of type "Enum" and not of type SiliconType...

2023-07-27 04:08 UTC, DEATHB4DEFEAT approved these changes
:godmode:

2023-07-27 04:10 UTC, merged